# <font color="red"> MBA em IA e Big Data</font>
## <span style="color:red">Linguagens e Ferramentas para Inteligência Artificial e Big Data (Python e SQL)</span>

### <span style="color:darkred">Python II, Pandas II e Numpy</span>

## Exercícios

*Moacir Antonelli Ponti*<br>
*ICMC/USP São Carlos*

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

# Parte 1 - Python 

### Exercício 1)

Codifique uma função que use comprehension para retornar uma lista com `n` valores numéricos iniciando em 0 e  com passo `p` permitindo um número float como passo. Arredonde cada número para 5 casas decimais usando a função `round(,5)`

Exemplo para n=8, p=0.05
```
[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]
```

### Exercício 2)

A partir de um vetor com números inteiros aleatórios, calcular seu `log` e criar uma lista com o resultado.
* se o número for 0 substituir o valor por `nan` (not a number) da biblioteca `math` para indicar que o resultado não é numérico

### Exercício 3)


Codifique uma função que receba como argumento duas listas de números com o mesmo tamanho. Use comprehension para retornar uma nova lista que é a multiplicação elemento-a-elemento das duas listas.  Caso as listas não possuam o mesmo tamanho emita uma mensagem de erro e retorne a constante `math.nan` do módulo `math`.

Exemplo:
```
l1 = [1, 2, 3, 4, 5]
l2 = [5, 5, 5, 10, 10]
multiplica_listas(l1,l2)

  [5, 10, 15, 40, 50]
```

### Exercício 4)

Codifique uma comprehension que simule uma matriz de tamanho n x n, cujos elementos são dados por `(i+j*i)`, sendo `i` o índice da linha e `j` o índice da coluna. Para simular isso com uma lista de listas, o `i` corresponde ao índice da lista principal e o `j` aos índices das listas aninhadas.

Por exemplo, seja a segunda lista (posição i=1), o seu terceiro elemento (posição j=2) seria obtido por `1+2*1 = 3`

Exemplo com n = 3:
```
  [[0, 0, 0],
   [1, 2, 3],
   [2, 4, 6]] 
```

---

##  <font color="red">Desafio</font>

Temos uma série de pontos 3D organizados numa lista e gostaríamos de computar as distâncias entre todos os pontos pareados.

Calcular a distância entre dois pontos $p1 = (x_1,y_1,z_1)$ e  $p2 = (x_2,y_2,z_2)$ usando a fórmula

$$d(p1,p2) = |x_1 - x_2| +|y_1 - y_2| + |z_1 - z_2|,$$
em que $|.|$ representa o valor absoluto.

Exemplo com 2 pontos organizados em listas:
```
[[1.0, 1.0, 1.0],
 [3.0, 3.0, 3.0]]
```

A saída deve ser:
```
[[0.0, 6.0],
 [6.0, 0.0]]
```

Note que a diagonal principal tem sempre valor zero já que representa a distância de um ponto para ele mesmo, e que a matriz é simétrica pois a distância entre dois pontos p1 e p2 é tal que: d(p1,p2) = d(p2,p1).

Para isso utilize uma única linha contendo comprehensions aninhadas e com iteração em paralelo

In [2]:
pontos3d = [ [1.0, 1.0, 1.0],
             [0.0, 1.0, 3.0],
             [2.0, 2.0, 2.0],
             [0.0, 0.0, 0.0] ]


### Exercício 5)

Escreva uma expressão lambda que permita receber uma string contendo duas palavras relativas ao nome de uma pessoa e seu sobrenome. Essas são separadas por um ou mais espaços em branco. A expressão deve retornar o nome no formato: "SOBRENOME, N."

Exemplo:
```
nome = 'Dennis   ritchie'
```

Retorno:
```
RITCHIE, D.
```

A seguir escreva um comprehension que percorra uma lista contendo nomes e gere uma nova lista com os nomes no formato "SOBRENOME, N."

Exemplo:
```
nomes = ['Dennis   ritchie', 'ALAN  Turing', 'betty Holberton']
```

Retorno:
```
['RITCHIE, D.', 'TURING, A.', 'HOLBERTON, B.']
```

----

# Parte 2 - Numpy


## Exercício 6) 

Dada uma lista de tuplas, em que cada tupla é formada por um par (str,list). Ver um exemplo abaixo.

```
l_tup = [('a',[8, 4, 6, 1]), ('b',[1, 2, 3, 4]), ('c',[5, 3, 3, 3])]
```
* Converta a lista de tuplas em um numpy array bidimensional em que cada lista é transformada em uma linha do array, ignorando a string. 
* Percorra cada linha do array resultante usando `for`, exibindo na tela os 3 últimos elementos de cada array

Seu código deve funcionar para qualquer número de tuplas na lista, assuma que as listas tem sempre o mesmo número de elementos, todos numéricos.


In [3]:
l_tup = [('a',[8, 4, 6, 1]), ('b',[1, 2, 3, 4]), ('c',[5, 3, 3, 3])]

## Exercício 7) 

Use o método `randint` do `numpy` para criar um array bidimensional com 6x10 elementos inteiros entre 1 e 5. 

A seguir, considerando apenas a submatriz formada pelas linhas: 2 até 6 e as colunas 2, 5 e 8, copie para uma matriz unidimensional os valores maiores ou iguais a 4.

# Exercício 8)


Dados dois arrays conforme abaixo que são notas (de 1 a 10) dadas a 4 diferentes serviços fornecidos por empresas concorrentes A e B. As notas de cada serviço estão organizadas nas 4 linhas dos arrays.

A empresa `A` coletou 10 notas, e `B` coletou 5 notas para cada serviço (simuladas aleatoriamente no código abaixo).

Os 4 serviços possuem pesos que é determinado pela lista `pesos` listada abaixo.

A empresa A deseja se comparar com a empresa B com base na média das notas da empresa B. Para isso:
1. usando redução, obtenha a média das notas de cada serviço da empresa B;
2. para cada serviço, calcule qual foi a menor nota observada por A considerando apenas as notas de A que foram maiores do que a média de B para aquele serviço;
3. armazene essas notas mínimas em um novo array de 4 elementos, e exiba esse array na tela;
4. utilizando multiplicação vetorial, calcule e exiba na tela a soma das notas mínimas ponderadas pelos pesos 


In [5]:
import numpy as np
A = np.random.randint(low=1,high=10,size=(4,20))
B = np.random.randint(low=1,high=10,size=(4,10))
pesos = [0.15, 0.25, 0.3, 0.3]
print(A)
print(B)
print(pesos)

[[1 8 9 6 2 4 4 3 7 7 8 4 2 9 6 1 3 4 5 8]
 [8 6 4 1 3 6 1 8 5 5 3 1 2 3 4 6 6 3 2 9]
 [9 3 6 4 5 8 1 8 7 4 9 8 1 9 5 5 5 7 9 4]
 [2 2 5 7 8 4 2 7 8 8 1 5 2 8 3 3 1 2 8 6]]
[[8 9 9 1 6 3 6 7 7 7]
 [5 4 6 1 6 6 8 4 3 6]
 [4 7 3 6 7 6 9 6 7 5]
 [2 7 8 5 2 8 9 4 4 5]]
[0.15, 0.25, 0.3, 0.3]


----

# Parte 3 - Pandas

### Exercício 9) 

Carregue o arquivo `tips.csv`:
1. Filtre as linhas selecionando apenas jantares (time = 'Dinner') e cuja conta foi superior a 40 (total_bill > 40), mostrando o total da conta, número de pessoas na mesa e gorjeta (total_bill, size, tip);
2. Obtenha um novo dataframe em que seja mostrada a gorjeta (tip) média e máxima para cada valor de dia da semana (day) e horário (time)

In [1]:
import pandas as pd

dtips = pd.read_csv('tips.csv')

### Exercício 10) 

Carregue os arquivos `sales1.csv`, `sales1_shipdate.csv`  e `sales2.csv`, os quais possuem informações de vendas realizadas. Devemos juntar as bases de dados e tratá-las. 

O arquivo `sales1_shipdate.csv` contém as datas de envio das ordens na `sales1.csv`. Já `sales2.csv` contém essa coluna no próprio arquivo

Para isso:

1. Combine as bases de dados, consolidando-as em um único DataFrame
2. Exiba na tela quais atributos possuem dados faltantes após a concatenação
    * Sabendo que `Total Revenue` é a multiplicação do preço unitário pela quantidade de unidades, preencha os valores faltantes dessa coluna
3. Detecte linhas duplicadas. Remova duplicatas, mantendo a primeira ocorrência, e imprima na tela quantas linhas foram removidas

In [2]:
import pandas as pd
import numpy as np

s1 = pd.read_csv('sales1.csv')
s1_ship = pd.read_csv('sales1_shipdate.csv')
s2 = pd.read_csv('sales2.csv')

## 1 - Combinar as bases de dados

In [3]:
## 2 - Atributos com dados faltantes 

In [4]:
## 3 - Tratamento de duplicatas