# <font color="red"> MBA em IA e Big Data</font>
## <span style="color:red">Linguagens e Ferramentas para Inteligência Artificial e Big Data (Python e SQL)</span>

### <span style="color:darkred">Python II, Pandas II e Numpy</span>

## Exercícios com soluções

*Moacir Antonelli Ponti*<br>
*ICMC/USP São Carlos*

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

# Parte 1 - Python 

### Exercício 1)

Codifique uma função que use comprehension para retornar uma lista com `n` valores numéricos iniciando em 0 e  com passo `p` permitindo um número float como passo. Arredonde cada número para 5 casas decimais usando a função `round(,5)`

Exemplo para n=8, p=0.05
```
[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]
```

In [4]:
def frange(n,p):
    lista = [round(x*p,5) for x in range(n+1)]
    return lista

lista = frange(8,0.05)
print(len(lista))
print(lista)

9
[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]


### Exercício 2)

A partir de um vetor com números inteiros aleatórios, calcular seu `log` e criar uma lista com o resultado.
* se o número for 0 substituir o valor por `nan` (not a number) da biblioteca `math` para indicar que o resultado não é numérico

In [5]:
import random as rd

n = 25
rand_num = [rd.randint(0,10) for _ in range(n)]
print(rand_num)

[3, 3, 9, 7, 6, 9, 1, 0, 9, 2, 8, 4, 9, 6, 10, 0, 0, 6, 8, 5, 8, 2, 8, 0, 9]


In [6]:
from math import nan, log
log_num = [log(x) if x != 0 else nan for x in rand_num]
print(log_num)

[1.0986122886681098, 1.0986122886681098, 2.1972245773362196, 1.9459101490553132, 1.791759469228055, 2.1972245773362196, 0.0, nan, 2.1972245773362196, 0.6931471805599453, 2.0794415416798357, 1.3862943611198906, 2.1972245773362196, 1.791759469228055, 2.302585092994046, nan, nan, 1.791759469228055, 2.0794415416798357, 1.6094379124341003, 2.0794415416798357, 0.6931471805599453, 2.0794415416798357, nan, 2.1972245773362196]


### Exercício 3)


Codifique uma função que receba como argumento duas listas de números com o mesmo tamanho. Use comprehension para retornar uma nova lista que é a multiplicação elemento-a-elemento das duas listas.  Caso as listas não possuam o mesmo tamanho emita uma mensagem de erro e retorne a constante `math.nan` do módulo `math`.

Exemplo:
```
l1 = [1, 2, 3, 4, 5]
l2 = [5, 5, 5, 10, 10]
multiplica_listas(l1,l2)

  [5, 10, 15, 40, 50]
```

In [7]:
from math import nan
import sys

def multiplica_listas(l1,l2):
    if (len(l1) != len(l2)):
        print('Erro: Listas devem ter o mesmo tamanho', file=sys.stderr)
        return nan
    else:
        return [x*y for x,y in zip(l1,l2)]

In [8]:
l1 = [1, 2, 3, 4, 5]
l2 = [5, 5, 5, 10, 10]

print(multiplica_listas(l1,l2))

l3 = [3, 4, 5]
print(multiplica_listas(l1,l3))

[5, 10, 15, 40, 50]
nan


Erro: Listas devem ter o mesmo tamanho


### Exercício 4)

Codifique uma comprehension que simule uma matriz de tamanho n x n, cujos elementos são dados por `(i+j*i)`, sendo `i` o índice da linha e `j` o índice da coluna. Para simular isso com uma lista de listas, o `i` corresponde ao índice da lista principal e o `j` aos índices das listas aninhadas.

Por exemplo, seja a segunda lista (posição i=1), o seu terceiro elemento (posição j=2) seria obtido por `1+2*1 = 3`

Exemplo com n = 3:
```
  [[0, 0, 0],
   [1, 2, 3],
   [2, 4, 6]] 
```

In [9]:
n = 3
matriz = [[i+j*i for j in range(n)] for i in range(n)]
print(matriz)

[[0, 0, 0], [1, 2, 3], [2, 4, 6]]


---

##  <font color="red">Solução do Desafio</font>

Temos uma série de pontos 3D organizados numa lista e gostaríamos de computar as distâncias entre todos os pontos pareados.

Calcular a distância entre dois pontos $p1 = (x_1,y_1,z_1)$ e  $p2 = (x_2,y_2,z_2)$ usando a fórmula

$$d(p1,p2) = |x_1 - x_2| +|y_1 - y_2| + |z_1 - z_2|,$$
em que $|.|$ representa o valor absoluto.

Exemplo com 2 pontos organizados em listas:
```
[[1.0, 1.0, 1.0],
 [3.0, 3.0, 3.0]]
```

A saída deve ser:
```
[[0.0, 6.0],
 [6.0, 0.0]]
```

Note que a diagonal principal tem sempre valor zero já que representa a distância de um ponto para ele mesmo, e que a matriz é simétrica pois a distância entre dois pontos p1 e p2 é tal que: d(p1,p2) = d(p2,p1).

Para isso utilize uma única linha contendo comprehensions aninhadas e com iteração em paralelo

In [10]:
from math import fabs, fsum

pontos3d = [ [1.0, 1.0, 1.0],
             [0.0, 1.0, 3.0],
             [2.0, 2.0, 2.0],
             [0.0, 0.0, 0.0] ]

dists = [[fsum([fabs(a-b) for a,b in zip(p1,p2)]) for p2 in pontos3d] for p1 in pontos3d ]

for linha in dists:
    print(linha)

[0.0, 3.0, 3.0, 3.0]
[3.0, 0.0, 4.0, 4.0]
[3.0, 4.0, 0.0, 6.0]
[3.0, 4.0, 6.0, 0.0]


### Exercício 5)

Escreva uma expressão lambda que permita receber uma string contendo duas palavras relativas ao nome de uma pessoa e seu sobrenome. Essas são separadas por um ou mais espaços em branco. A expressão deve retornar o nome no formato: "SOBRENOME, N."

Exemplo:
```
nome = 'Dennis   ritchie'
```

Retorno:
```
RITCHIE, D.
```

A seguir escreva um comprehension que percorra uma lista contendo nomes e gere uma nova lista com os nomes no formato "SOBRENOME, N."

Exemplo:
```
nomes = ['Dennis   ritchie', 'ALAN  Turing', 'betty Holberton']
```

Retorno:
```
['RITCHIE, D.', 'TURING, A.', 'HOLBERTON, B.']
```

In [11]:
f = lambda nome: nome.split()[-1].upper()+', '+nome.split()[0][0]+'.'
f('Moacir Ponti')

'PONTI, M.'

In [12]:
cientistas_da_computacao = ['Betty Holberton', 'Alan Turing', 'Dennis Ritchie', 'Grace Hopper', 'Donald Knuth', 'Charles Babbage', 'Ada Lovelace', 'Geoffrey Hinton', 'Daphne Koller']
formato = [f(nome) for nome in cientistas_da_computacao]
print(formato)

['HOLBERTON, B.', 'TURING, A.', 'RITCHIE, D.', 'HOPPER, G.', 'KNUTH, D.', 'BABBAGE, C.', 'LOVELACE, A.', 'HINTON, G.', 'KOLLER, D.']


In [13]:
f = lambda nome: nome.split()[-1].upper()+', '+nome.split()[0][0]+'.'
formato = [f(nome) for nome in cientistas_da_computacao]
for autor in formato:
    print(autor)

HOLBERTON, B.
TURING, A.
RITCHIE, D.
HOPPER, G.
KNUTH, D.
BABBAGE, C.
LOVELACE, A.
HINTON, G.
KOLLER, D.


----

# Parte 2 - Numpy


### Exercício 6) 

Dada uma lista de tuplas, em que cada tupla é formada por um par (str,list). Ver um exemplo abaixo.

```
l_tup = [('a',[8, 4, 6, 1]), ('b',[1, 2, 3, 4]), ('c',[5, 3, 3, 3])]
```
* Converta a lista de tuplas em um numpy array bidimensional em que cada lista é transformada em uma linha do array, ignorando a string. 
* Percorra cada linha do array resultante usando `for`, exibindo na tela os 3 últimos elementos de cada array

Seu código deve funcionar para qualquer número de tuplas na lista, assuma que as listas tem sempre o mesmo número de elementos, todos numéricos.


In [14]:
l_tup = [('a',[8, 4, 6, 1]), ('b',[1, 2, 3, 4]), ('c',[5, 3, 3, 3])]

In [15]:
import numpy as np

arr = np.array([el[1] for el in l_tup])

for l in arr:
    print(l[-3:])

[4 6 1]
[2 3 4]
[3 3 3]


### Exercício 7) 

Use o método `randint` do `numpy` para criar um array bidimensional com 6x10 elementos inteiros entre 1 e 5. 

A seguir, considerando apenas a submatriz formada pelas linhas: 2 até 6 e as colunas 2, 5 e 8, copie para uma matriz unidimensional os valores maiores ou iguais a 4.

In [16]:
x = np.random.randint(1,6,60).reshape(6,10)
print(x)

[[3 1 3 5 1 5 5 3 5 1]
 [3 5 1 2 4 5 4 4 5 1]
 [3 1 4 5 4 4 5 5 4 3]
 [3 1 4 4 2 4 4 5 5 1]
 [1 3 4 3 1 2 4 5 5 2]
 [2 2 1 1 4 3 3 1 5 2]]


In [17]:
subx = x[2:,[2,5,8]]
vec = np.copy(subx[subx>=4])
print(vec)

[4 4 4 4 4 5 4 5 5]


# Exercício 8)


Dados dois arrays conforme abaixo que são notas (de 1 a 10) dadas a 4 diferentes serviços fornecidos por empresas concorrentes A e B. As notas de cada serviço estão organizadas nas 4 linhas dos arrays.

A empresa `A` coletou 10 notas, e `B` coletou 6 notas para cada serviço (simuladas aleatoriamente no código abaixo).

Os 4 serviços possuem pesos que é determinado pela lista `pesos` listada abaixo.

A empresa A deseja se comparar com a empresa B com base na média das notas da empresa B. Para isso:
1. usando redução, obtenha a média das notas de cada serviço da empresa B;
2. para cada serviço, calcule qual foi a menor nota observada por A considerando apenas as notas de A que foram maiores do que a média de B para aquele serviço;
3. armazene essas notas mínimas em um novo array de 4 elementos, e exiba esse array na tela;
4. utilizando multiplicação vetorial, calcule e exiba na tela a soma das notas mínimas ponderadas pelos pesos 


In [33]:
A = np.random.randint(low=1,high=11,size=(4,10))
B = np.random.randint(low=1,high=11,size=(4,6))
pesos = [0.15, 0.25, 0.3, 0.3]
print(A)
print(B)
print(pesos)

[[ 9  1  8  3  6  4  3  4  1  2]
 [ 7  5  5  4  7  7  6  2  5  6]
 [ 6  7  4  5  1  9  5  8  7  2]
 [ 5  5 10  4  4  2  2  2  3  4]]
[[ 6  4 10  1  4  3]
 [ 8  1  1 10 10  7]
 [ 3  7  9  1  5  9]
 [ 6  5  5  8  2  6]]
[0.15, 0.25, 0.3, 0.3]


In [40]:
####
mins = []
for i,m in zip(range(B.shape[0]), np.mean(B,axis=1)):
    minv = np.min(A[i,:][A[i,:] > m])
    mins.append(minv)

mins = np.array(mins)
pesos = np.array(pesos)
print('1) Medias de B:', np.round(np.mean(B,axis=1),2))
print('2/3) Menores notas de A > do que medias de B:', mins)
print('  pesos=', pesos)
print('4) Soma ponderada:', np.round(mins.dot(pesos),2))


1) Medias de B: [4.67 6.17 5.67 5.33]
2/3) Menores notas de A > do que medias de B: [ 6  7  6 10]
  pesos= [0.15 0.25 0.3  0.3 ]
4) Soma ponderada: 7.45


----

# Parte 3 - Pandas

### Exercício 9) 

Carregue o arquivo `tips.csv`:
1. Filtre as linhas selecionando apenas jantares (time = 'Dinner') e cuja conta foi superior a 40 (total_bill > 40), mostrando o total da conta, número de pessoas na mesa e gorjeta (total_bill, size, tip);
2. Obtenha um novo dataframe em que seja mostrada a gorjeta (tip) média e máxima para cada valor de dia da semana (day) e horário (time)

In [43]:
import pandas as pd

dtips = pd.read_csv('tips.csv')

print(dtips.loc[(dtips['time']=='Dinner') & (dtips['total_bill']>40), 
          ['total_bill', 'size', 'tip'] ])

avgtip = dtips.groupby(['day','time'])['tip'].agg([np.mean, np.max])
print(avgtip)

     total_bill  size    tip
59        48.27     4   6.73
95        40.17     4   4.73
102       44.30     3   2.50
156       48.17     6   5.00
170       50.81     3  10.00
182       45.35     3   3.50
184       40.55     2   3.00
211       48.33     4   9.00
                 mean   amax
day  time                   
Fri  Dinner  2.940000   4.73
     Lunch   2.282500   3.48
Sat  Dinner  3.019647  10.00
Sun  Dinner  3.255132   6.50
Thur Dinner  3.000000   3.00
     Lunch   2.780500   6.70


### Exercício 10) 

Carregue os arquivos `sales1.csv`, `sales1_shipdate.csv`  e `sales2.csv`, os quais possuem informações de vendas realizadas. Devemos juntar as bases de dados e tratá-las. 

O arquivo `sales1_shipdate.csv` contém as datas de envio das ordens na `sales1.csv`. Já `sales2.csv` contém essa coluna no próprio arquivo

Para isso:

1. Combine as bases de dados, consolidando-as em um único DataFrame
2. Exiba na tela quais atributos possuem dados faltantes após a concatenação
    * Sabendo que `Total Revenue` é a multiplicação do preço unitário pela quantidade de unidades, preencha os valores faltantes dessa coluna
3. Detecte linhas duplicadas. Remova duplicatas, mantendo a primeira ocorrência, e imprima na tela quantas linhas foram removidas

In [45]:
import pandas as pd
import numpy as np

s1 = pd.read_csv('sales1.csv')
s1_ship = pd.read_csv('sales1_shipdate.csv')
s2 = pd.read_csv('sales2.csv')

## 1 - Combinar as bases de dados

# juntar data do envio pelo Order ID
s1 = pd.merge(s1,s1_ship,on='Order ID',how='outer')
# concatenar os dois DataFrames
sales = pd.concat([s1,s2],axis=0)

sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102 entries, 0 to 87
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country         102 non-null    object 
 1   Item Type       102 non-null    object 
 2   Online          93 non-null     float64
 3   Order Priority  102 non-null    object 
 4   Order Date      102 non-null    object 
 5   Order ID        102 non-null    int64  
 6   Units Sold      102 non-null    int64  
 7   Unit Price      102 non-null    float64
 8   Total Cost      102 non-null    float64
 9   Total Profit    102 non-null    float64
 10  Ship Date       100 non-null    object 
 11  Total Revenue   88 non-null     float64
dtypes: float64(5), int64(2), object(5)
memory usage: 10.4+ KB


In [46]:
## 2 - Atributos com dados faltantes 

for (colName, colData) in sales.iteritems():
    if (np.any(pd.isna(colData))):
        print(colName)

Online
Ship Date
Total Revenue


In [47]:
ind_falt = sales['Total Revenue'].isna()
print(sales.loc[ind_falt])

                  Country        Item Type  Online Order Priority Order Date  \
0                  Tuvalu        Baby Food     0.0              H  5/28/2010   
1                  Brazil           Cereal     1.0              C  8/22/2012   
2                  Russia  Office Supplies     0.0              L   5/2/2014   
3   Sao Tome and Principe           Fruits     1.0              C  6/20/2014   
4                  Rwanda  Office Supplies     0.0              L   2/1/2013   
5         Solomon Islands        Baby Food     1.0              C   2/4/2015   
6                  Angola        Household     0.0              M  4/23/2011   
7            Burkina Faso       Vegetables     1.0              H  7/17/2012   
8   Republic of the Congo    Personal Care     0.0              M  7/14/2015   
9                 Senegal           Cereal     1.0              H  4/18/2014   
10             Kyrgyzstan       Vegetables     1.0              H  6/24/2011   
11             Cape Verde          Cloth

In [48]:
sales.loc[ind_falt].apply(lambda x: x['Units Sold']*x['Unit Price'], axis=1)
sales.loc[ind_falt, 'Total Revenue'] = sales.loc[ind_falt].apply(lambda x: x['Units Sold']*x['Unit Price'], axis=1)
print(sales.loc[ind_falt])

                  Country        Item Type  Online Order Priority Order Date  \
0                  Tuvalu        Baby Food     0.0              H  5/28/2010   
1                  Brazil           Cereal     1.0              C  8/22/2012   
2                  Russia  Office Supplies     0.0              L   5/2/2014   
3   Sao Tome and Principe           Fruits     1.0              C  6/20/2014   
4                  Rwanda  Office Supplies     0.0              L   2/1/2013   
5         Solomon Islands        Baby Food     1.0              C   2/4/2015   
6                  Angola        Household     0.0              M  4/23/2011   
7            Burkina Faso       Vegetables     1.0              H  7/17/2012   
8   Republic of the Congo    Personal Care     0.0              M  7/14/2015   
9                 Senegal           Cereal     1.0              H  4/18/2014   
10             Kyrgyzstan       Vegetables     1.0              H  6/24/2011   
11             Cape Verde          Cloth

In [49]:
for (colName, colData) in sales.iteritems():
    if (np.any(pd.isna(colData))):
        print(colName)

Online
Ship Date


In [51]:
## 3 - Tratamento de duplicatas
print(sales[sales.duplicated(keep=False)])

print(sales.shape)
sales = sales.drop_duplicates(keep='first')
print(sales.shape)

Empty DataFrame
Columns: [Country, Item Type, Online, Order Priority, Order Date, Order ID, Units Sold, Unit Price, Total Cost, Total Profit, Ship Date, Total Revenue]
Index: []
(101, 12)
(101, 12)
