# <font color="red"> MBA em IA e Big Data</font>
## <span style="color:red">Linguagens e Ferramentas para Inteligência Artificial e Big Data (Python e SQL)</span>

### <span style="color:darkred">Numpy: parte 2</span>

*Moacir Antonelli Ponti*<br>
*ICMC/USP São Carlos*

*(com materiais do Prof. Luis Gustavo Nonato)*

- *Broadcasting*
- Comparações
- Reduções
- Aritmética vetorial

# Broadcasting (extensão)

Garante eficiência computacional por extensão de arrays
- operações aritméticas: soma, subtração, multiplicação e divisão) são feitas elemento a elemento (*element-wise*)
- __broadcasting__ transforma os operandos de modo que tenham as mesmas dimensões

### Operações entre um array e um escalar

Ao operar um escalar `s` e um array `A`, `numpy` replica o escalar em um array com a mesma dimensão de A

Abaixo, a matriz `A` é somada com o escalar `3`. 

O __broadcasting__ replica o escalar um array 5x5 e então os dois arrays são somados elemento a elemento.
```python
A = np.arange(25).reshape(5,5) # matriz 5x5
s = 3                          # escalar
B = s+A                        # matriz 5x5
```
$$
B = s + A = \left[\begin{array}{ccccc}
3 & 3 & 3 & 3 & 3\\
3 & 3 & 3 & 3 & 3\\
3 & 3 & 3 & 3 & 3\\
3 & 3 & 3 & 3 & 3\\
3 & 3 & 3 & 3 & 3
\end{array}\right] + 
\left[\begin{array}{ccccc} 
0  & 1 & 2 & 3 & 4 \\
5  & 6 & 7 & 8 & 9\\
10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19\\
20 & 21 & 22 & 23 & 24
\end{array}\right]
$$

In [2]:
import numpy as np

# Cria uma matriz 5x5 com números aleatórios
A = np.arange(25).reshape(5,5)

# define um escalar
s = 3

# O opeador "+" é aplicado elemento por elemento (caso contrário não seria definido)
B = s + A

print(A,'\n')
print(B)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]
 [23 24 25 26 27]]


#### Operações entre arrays
Em pares de arrays também ocorre extensão, porém restrições devem ser respeitadas:
- Os dois arrays devem possuir dimensões compatíveis em algum(s) dos eixos
- O broadcasting é aplicado nos demais eixos para que ambos os arrays tenham as mesmas dimensões
```python
A = np.arange(25).reshape(5,5) # matriz 5x5
v = np.arange(5)               # array com 5 elementos
B = v*A                        # matriz 5x5
```
$$
B = v * A 
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccccc}
0  & 1 & 2 & 3 & 4
\end{array}\right] * 
\left[\begin{array}{ccccc} 
0  & 1 & 2 & 3 & 4 \\
5  & 6 & 7 & 8 & 9\\
10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19\\
20 & 21 & 22 & 23 & 24
\end{array}\right] 
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccccc}
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4
\end{array}\right] * 
\left[\begin{array}{ccccc} 
0  & 1 & 2 & 3 & 4 \\
5  & 6 & 7 & 8 & 9\\
10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19\\
20 & 21 & 22 & 23 & 24
\end{array}\right]
$$

__Cuidado__: o operador `*` corresponde a uma multiplicação elemento por elemento, e *não* uma multiplicação matricial.

In [3]:
A = np.arange(25).reshape(5,5) # matriz 5x5
print('Matriz A:', A.shape)

v = np.arange(5)  # array com 5 elementos
                  # como a segunda dimensão não foi especificada, "v" é interpretado 
                  # como um sendo 1x5 (uma linha e 5 colunas)
        
print('Array "v": ', v.shape)
print('OBS: a segunda dimensão de "v" é livre ')

# A operação "*" é realizada elemento a elemento, 
# - estendendo o array "v" para gerar novas linhas
B = v * A

print(5*'---')
print('v = \n',v)
print('A = \n',A)
print('B = \n',B)

Matriz A: (5, 5)
Array "v":  (5,)
OBS: a segunda dimensão de "v" é livre 
---------------
v = 
 [0 1 2 3 4]
A = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
B = 
 [[ 0  1  4  9 16]
 [ 0  6 14 24 36]
 [ 0 11 24 39 56]
 [ 0 16 34 54 76]
 [ 0 21 44 69 96]]


__Broadcasting__ é feito nas colunas quando temos um array coluna
```python
v = np.arange(5).reshape(5,1) # array com 5 elementos 5 x 1
                              # i.e. 5 linhas e uma coluna
```
$$
B = v * A 
$$

$$
\downarrow
$$

$$
\left[\begin{array}{c}
0  \\ 1 \\ 2 \\ 3 \\ 4
\end{array}\right] * 
\left[\begin{array}{ccccc} 
0  & 1 & 2 & 3 & 4 \\
5  & 6 & 7 & 8 & 9\\
10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19\\
20 & 21 & 22 & 23 & 24
\end{array}\right] 
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccccc}
0  & 0 & 0 & 0 & 0\\
1  & 1 & 1 & 1 & 1\\
2  & 2 & 2 & 2 & 2\\
3  & 3 & 3 & 3 & 3\\
4  & 4 & 4 & 4 & 4
\end{array}\right] * 
\left[\begin{array}{ccccc} 
0  & 1 & 2 & 3 & 4 \\
5  & 6 & 7 & 8 & 9\\
10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19\\
20 & 21 & 22 & 23 & 24
\end{array}\right]
$$

In [4]:
A = np.arange(25).reshape(5,5) # matriz 5x5
print(A.shape)

v = np.arange(5).reshape(5,1) # array com 5 elementos 5x1
print(v.shape)

# A operação "*" é feita elemento por elemento, 
# broadcasting em "v" gerar novas colunas
B =  v * A

print(v,'\n')
print(A,'\n')
print(B)

(5, 5)
(5, 1)
[[0]
 [1]
 [2]
 [3]
 [4]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [20 22 24 26 28]
 [45 48 51 54 57]
 [80 84 88 92 96]]


Quando os dois operandos são arrays unidimensionais, sendo um deles array linha e o outro array coluna __Broadcasting__ é aplicado em ambos:
```python
v = np.arange(5)  # array com 5 elementos 1x5 (uma linha e 5 colunas)
w = np.arange(3).reshape(3,1) # array com 3 elementos 3x1
```
$$
Z = v + w
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccccc}
0  & 1 & 2 & 3 & 4
\end{array}\right] + 
\left[\begin{array}{c} 
0  \\
1 \\
2
\end{array}\right] 
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccccc}
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4
\end{array}\right] + 
\left[\begin{array}{ccccc} 
0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 1\\
2 & 2 & 2 & 2 & 2
\end{array}\right]
$$

In [5]:
v = np.arange(5)  # array com 5 elementos
                  # como a segunda dimensão não foi especificada, "v" é interpretado 
                  # como um sendo 1x5 (uma linha e 5 colunas)
print(v.shape)

w = np.arange(3).reshape(3,1) # array com 3 elementos 
                              # como a segunda dimensão foi especificada, "v" é um array 
                              # com 3 linhas e uma coluna
print(w.shape)

# A operação "+" é feita elemento por elemento, broadcasting "v" e "w" simultaneamente
# Neste caso "w" é um vetor coluna e "v" é tratado como vetor linha
Z =  v + w

print('array v:\n',v,'\n')
print('array w:\n',w,'\n')
print('array Z = v+w\n',Z)  
print(Z.shape) # note que o resultado é uma matriz 3x5

(5,)
(3, 1)
array v:
 [0 1 2 3 4] 

array w:
 [[0]
 [1]
 [2]] 

array Z = v+w
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]
(3, 5)


## Operadores relacionais

Operadores `==`, `>`,`<`,`>=`,`<=`, e `!=` são aplicados elemento a elemento.

In [6]:
A = np.arange(4).reshape(2,2)      # matriz 2x2
B = np.arange(6,2,-1).reshape(2,2) # matriz 2x2

M = (B == A)

print(A,'\n')
print(B,'\n')
print(M)

[[0 1]
 [2 3]] 

[[6 5]
 [4 3]] 

[[False False]
 [False  True]]


#### Igualdade do array com `np.array_equal()`

In [7]:
A = np.arange(4).reshape(2,2)      # matrix 2x2
B = np.arange(6,2,-1).reshape(2,2) # matrix 2x2
C = np.copy(A)

# Resposta é apenas um valor booleano
print(np.array_equal(A,B))
print(np.array_equal(A,C))

False
True


# Redução

> Métodos aplicados ao array como um todo ou somente às linhas ou colunas.

O parâmetro 'axis' controla a direção: 
- 'axis' não especificado: retorna um valor único, opera sobre todo o array
- 'axis=0' redução nas colunas (percorre as linhas): retorna um array com número de elementos igual ao número de colunas
- 'axis=1' redução nas linhas (percorre as colunas): retorna um array com número de elementos igual ao número de linhas


### Redução lógica
- `all`: verifica se **todos** os elementos do array satisfazem a condição (True)
- `any`: verifica se **algum** elemento do array satisfaz a condição (True)

In [8]:
# np.array_equal(A,B) é equivalente a:
D = (A==B)
print(D)

[[False False]
 [False  True]]


In [9]:
print(np.all(D))

False


In [10]:
A = np.arange(25).reshape(5,5)
print(A,'\n')

M = A > 0
print(M,'\n')

print('Todos os elementos são TRUE? ', np.all(M))
print('Algum elemento é TRUE? ',np.any(M))

print('Todos os elementos de cada coluna são TRUE? ',np.all(M,axis=0))
print('Algum elemento de cada linha é TRUE? ',np.any(M,axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] 

Todos os elementos são TRUE?  False
Algum elemento é TRUE?  True
Todos os elementos de cada coluna são TRUE?  [False  True  True  True  True]
Algum elemento de cada linha é TRUE?  [ True  True  True  True  True]


#### Mais reduções

Aritméticas e estatísticas: 

`sum`, `mean`, `median`, `std` (desvio padrão), `min`,  `max`, `argmin`, `argmax` 

In [11]:
A = np.zeros((6,5))  # matriz 5x5 de zeros
A[:] = np.arange(5)  # broadcasting o array [0,1,2,3,4] nas linhas

print(A,'\n')

print('Soma de todos os valores: ', np.sum(A)) # todos os elementos
print('Soma dos valores das colunas: ', np.sum(A,axis=0)) # soma os valores das colunas
print('Soma dos valores das linhas: ', np.sum(A,axis=1)) # soma os valores das linhas

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]] 

Soma de todos os valores:  60.0
Soma dos valores das colunas:  [ 0.  6. 12. 18. 24.]
Soma dos valores das linhas:  [10. 10. 10. 10. 10. 10.]


In [12]:
A = np.random.randint(low=0,high=30,size=(5,5)) # matriz 5x5 com números inteiros 
                                                # randomicos no intervalor entre 0 e 30
print(A,'\n')

# todos os elementos
print('Maior valor dentre todos na matriz: ',np.max(A))    # maior valor da matriz
print('Posição do maior valor dentre todos na matriz: ',np.argmax(A)) # lineariza a matriz com A.ravel() e 
                                                                      # retorna a posicão do maior valor
# Por coluna
print('Maior valor em cada coluna: ',np.max(A,axis=0))  # maior valor em cada coluna
print('Posição do maior valor em cada coluna: ',np.argmax(A,axis=0)) # posição do maior valor em cada coluna

[[11 12 15  1 19]
 [ 3 10  8  9 18]
 [ 4 10 22  9 13]
 [22 28 22 26 27]
 [16  9  5 18 28]] 

Maior valor dentre todos na matriz:  28
Posição do maior valor dentre todos na matriz:  16
Maior valor em cada coluna:  [22 28 22 26 28]
Posição do maior valor em cada coluna:  [3 3 2 3 4]


In [13]:
A = np.random.randint(low=0,high=30,size=(5,5)).astype(float)
print(A,'\n')

print('Media de todos os valores: ',np.mean(A))   # média de todos os valores
print('Media por coluna: ',np.mean(A,axis=0))     # média por coluna
print('Media por linha: ',np.mean(A,axis=1))      # média por linha

[[16. 18.  3. 13. 20.]
 [17. 17. 23. 12. 10.]
 [12.  7. 21. 20. 23.]
 [21. 28. 29.  8. 11.]
 [16.  8. 11.  6. 14.]] 

Media de todos os valores:  15.36
Media por coluna:  [16.4 15.6 17.4 11.8 15.6]
Media por linha:  [14.  15.8 16.6 19.4 11. ]


## Ordenação  `sort()`


- Quando o método é invocado utilizando a própria variável, a ordenação é feita diretamente no array (`inplace`). Por exemplo:

- Usando o `numpy.sort()` uma cópia ordenada do array é gerada (o array original não é modificado).

Por padrão a ordenação é feita em cada linha (`axis=1` é o valor padrão do parâmetro 'axis') 

In [14]:
A = np.random.randint(low=0,high=30,size=(5,5))
print('Array original "A": \n',A,'\n')

B = np.sort(A) # `B` é uma cópia de `A` com linhas ordenas
print('"B" é cópia de "A" com valores das linhas ordenados. Array "A" não é alterado:')
print('B = \n',B,'\n')
print('A = \n',A,'\n')

Array original "A": 
 [[22 17  5 24  1]
 [11 27 18 18  1]
 [25  1 17 26 29]
 [23 25 19 26 17]
 [25 15  0 19 10]] 

"B" é cópia de "A" com valores das linhas ordenados. Array "A" não é alterado:
B = 
 [[ 1  5 17 22 24]
 [ 1 11 18 18 27]
 [ 1 17 25 26 29]
 [17 19 23 25 26]
 [ 0 10 15 19 25]] 

A = 
 [[22 17  5 24  1]
 [11 27 18 18  1]
 [25  1 17 26 29]
 [23 25 19 26 17]
 [25 15  0 19 10]] 



In [15]:
A.sort()  # as linhas de `A` são ordenadas modificando o array original
print('Os valores das linhas do array "A" são ordenados: \n A =\n',A,'\n')

A.sort(axis=0) # as COLUNAS de `A` são ordenadas modificando o array original
print('Os valores das colunas são ordenadas:  \n A =\n',A,'\n')

Os valores das linhas do array "A" são ordenados: 
 A =
 [[ 1  5 17 22 24]
 [ 1 11 18 18 27]
 [ 1 17 25 26 29]
 [17 19 23 25 26]
 [ 0 10 15 19 25]] 

Os valores das colunas são ordenadas:  
 A =
 [[ 0  5 15 18 24]
 [ 1 10 17 19 25]
 [ 1 11 18 22 26]
 [ 1 17 23 25 27]
 [17 19 25 26 29]] 



## Aritmétrica vetorial e matricial

> A multiplicação matriz e vetor (ou matriz e matriz) como definida na álgebra matricial é feita utilizando o método `dot()`

As dimensões devem ser compatíveis

$$
b1 = \left[\begin{array}{cc}
           1 & 1 \\
           2 & 2
    \end{array}\right]\cdot
    \left[\begin{array}{c}
           1  \\
           2 
    \end{array}\right] = \left[\begin{array}{c}
           3  \\
           6 
    \end{array}\right]
$$

$$
b2 = \left[\begin{array}{cc}
           1 & 2 
    \end{array}\right]\cdot
\left[\begin{array}{cc}
           1 & 1 \\
           2 & 2
    \end{array}\right]\cdot
     = \left[\begin{array}{cc}
           5 & 5
    \end{array}\right]
$$

In [16]:
A = np.zeros((2,2))      # matrix 2x2 de zeros  
v = np.array([1,2]).reshape(2,1) # array 2x1
A[:] = v                # broadcasting o array 2x1 nas colunas da matriz 'A'

print('Matriz 2x2 A:\n',A)
print('Vetor 2x1 v:\n',v)

print('\n Multiplicando a matriz A pelo vetor v resulta em um vetor 2x1')
b1 = np.dot(A,v)   # v e b1 são vetores colunas 
print(b1,b1.shape)

#### Atenção ####
# O produto np.dot(v,A) não é válido, pois as dimensões não são compatíveis 
# (produto de vetor 2x1 com matriz 2x2 não existe tente gerar o produto e veja a mensagem de erro)

# Para compadibilizarmos as dimensão precisamos transpor o vetor v
# (produto de vetor 1x2 com matriz 2x2 é bem definido e resulta em um vetor 1x2
print('\n Multiplicando o vetor transposto v.T pela matriz A pelo resulta em um vetor 1x2')
b2 = np.dot(v.T, A) # v.T é um vetor linha, assim como b2
print(b2,b2.shape)

Matriz 2x2 A:
 [[1. 1.]
 [2. 2.]]
Vetor 2x1 v:
 [[1]
 [2]]

 Multiplicando a matriz A pelo vetor v resulta em um vetor 2x1
[[3.]
 [6.]] (2, 1)

 Multiplicando o vetor transposto v.T pela matriz A pelo resulta em um vetor 1x2
[[5. 5.]] (1, 2)


---

#### <font color="blue">Exercício 2.8</font>

Dados dois arrays conforme abaixo que são notas (de 1 a 10) dadas a 4 diferentes serviços fornecidos por empresas concorrentes A e B. As notas de cada serviço estão organizadas nas 4 linhas dos arrays.

A empresa `A` coletou 20 notas, e `B` coletou 10 notas para cada serviço (simuladas aleatoriamente no código abaixo).

Os 4 serviços possuem pesos que é determinado pela lista `pesos` listada abaixo.

A empresa A deseja se comparar com a empresa B com base na média das notas da empresa B. Para isso:
1. usando redução, obtenha a média das notas de cada serviço da empresa B;
2. para cada serviço, calcule qual foi a menor nota observada por A considerando apenas as notas de A que foram maiores do que a média de B para aquele serviço;
3. armazene essas notas mínimas em um novo array de 4 elementos, e exiba esse array na tela;
4. utilizando multiplicação vetorial, calcule e exiba na tela a soma das notas mínimas ponderadas pelos pesos 

---

In [17]:
A = np.random.randint(low=1,high=10,size=(4,20))
B = np.random.randint(low=1,high=10,size=(4,10))
pesos = [0.15, 0.25, 0.3, 0.3]
print(A, '\n')
print(B, '\n')
print(pesos, '\n')

[[9 7 4 8 1 5 6 5 1 3 4 7 8 5 5 2 6 7 1 6]
 [7 7 6 6 2 3 5 5 6 9 3 1 9 8 5 5 3 6 7 4]
 [1 4 4 7 1 2 9 3 8 5 2 1 6 2 6 9 9 3 5 5]
 [8 4 4 1 3 1 6 6 5 1 7 4 6 7 7 6 2 7 1 7]] 

[[9 8 8 1 7 4 1 6 6 1]
 [9 6 6 7 7 8 7 5 3 3]
 [7 5 7 9 6 5 8 9 8 3]
 [5 3 5 2 6 7 6 4 1 5]] 

[0.15, 0.25, 0.3, 0.3] 



In [33]:
#1
media_nota_b = np.mean(B, axis=1)
media_nota_b

array([5.1, 6.1, 6.7, 4.4])

In [36]:
#2
menor_nota_a = []
for i, nota in enumerate(A):
    nota = nota[nota > media_nota_b[i]]
    menor_nota_a.append(np.min(nota))

menor_nota_a

array([6, 7, 7, 5])

In [37]:
#3
menor_nota_a = np.array(menor_nota_a)
menor_nota_a

array([6, 7, 7, 5])

In [42]:
#4
com_pesos = menor_nota_a * pesos
print(np.sum(com_pesos))

6.25


In [43]:
com_pesos = menor_nota_a.dot(pesos)
com_pesos
print(com_pesos)


6.25


array([[0.72969849, 0.36856154],
       [0.87076971, 0.38303487],
       [0.27354838, 0.15476955],
       [0.44900772, 0.11069799],
       [0.36013611, 0.4124821 ],
       [0.57396247, 0.666706  ],
       [0.28924032, 0.19646029],
       [0.20307105, 0.76298499]])